# Generated by Django 3.0 on 2021-02-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='Transaksi',
            new_name='transaksi',
        ),
    ]
