# Generated by Django 3.0 on 2021-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20210216_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hargaperawatan',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
