# Generated by Django 3.0 on 2021-02-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_auto_20210216_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisperawatan',
            name='harga_perawatan',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='HargaPerawatan',
        ),
    ]
