# Generated by Django 3.0 on 2021-02-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_auto_20210217_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='Kelamin',
            field=models.CharField(choices=[('LAKI-LAKI', 'LAKI-LAKI'), ('PEREMPUAN', 'PEREMPUAN')], max_length=100),
        ),
    ]
