# Generated by Django 3.0 on 2021-02-22 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20210217_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transaksi',
            options={'ordering': ['-id']},
        ),
    ]
